version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope

  - package-ecosystem: npm
    directory: "/packages/eslint-config"
    schedule:
      interval: daily
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope

  - package-ecosystem: npm
    directory: "/packages/eslint-config-basic"
    schedule:
      interval: daily
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope

  - package-ecosystem: npm
    directory: "/packages/eslint-config-nuxt"
    schedule:
      interval: daily
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope

  - package-ecosystem: npm
    directory: "/packages/eslint-config-react"
    schedule:
      interval: daily
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope

  - package-ecosystem: npm
    directory: "/packages/eslint-config-ts"
    schedule:
      interval: daily
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope

  - package-ecosystem: npm
    directory: "/packages/eslint-config-vue"
    schedule:
      interval: daily
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope

  - package-ecosystem: npm
    directory: "/packages/prettier-config"
    schedule:
      interval: daily
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
